version: '3.2'
services:
  web:
    container_name: bot-mega
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "npm install && npx prisma generate && npm start"
